'use strict';
const assert = require('node:assert/strict');
const esbuild = require('esbuild');
const { resolve } = require('node:path');
const panel = resolve('../../mi-comercio-app');
esbuild.buildSync({ entryPoints: [resolve(panel, 'app/dashboard/reports/report-utils.ts')], bundle: true, platform: 'node', format: 'cjs', outfile: '.tmp/report-utils-test.cjs', tsconfig: resolve(panel, 'tsconfig.json') });
esbuild.buildSync({ entryPoints: [resolve(panel, 'lib/business-shared.ts')], bundle: true, platform: 'node', format: 'cjs', outfile: '.tmp/business-shared-test.cjs', tsconfig: resolve(panel, 'tsconfig.json') });
const { buildReportsSnapshot } = require('../.tmp/report-utils-test.cjs');
const { formatDisplayDate, formatCurrency } = require('../.tmp/business-shared-test.cjs');
const zone = 'America/Argentina/Buenos_Aires';
const today = new Intl.DateTimeFormat('en-CA', { timeZone: zone }).format(new Date());
process.env.TZ = 'Asia/Tokyo';
const snapshot = buildReportsSnapshot({ appointments: [], customers: [], expenses: [], payouts: [], services: [], staffMembers: [], staffTimeLogs: [], timeZone: zone, payments: [{ amount: 1234.56, status: 'completed', method: 'cash', collectionDate: today, processedAt: null }], workRecords: [{ workDate: today, amount: 1234.56, serviceName: 'Corte de prueba' }] }, 'day');
assert.equal(snapshot.revenue, 1234.56);
assert.equal(snapshot.workSummary.count, 1);
assert.equal(snapshot.workSummary.amount, 1234.56);
assert.equal(snapshot.appointmentsCount, 0);
assert.match(formatDisplayDate('2026-09-09', zone), /9 sept/);
assert.match(formatCurrency(1234.56), /1\.234,56/);
console.log('PASS: historical report dates remain literal across browser time zones; work values and receipts are separate, without fabricated appointments.');
