'use client';
import { useEffect, useState, type FormEvent } from 'react';
type Account={email:string;name:string;phone:string};
async function request(path:string,method='GET',data?:unknown) {
 const r=await fetch('/api/cuenta/'+path,{method,cache:'no-store',headers:{'Content-Type':'application/json'},body:data?JSON.stringify(data):undefined});
 const result=await r.json();if(!r.ok) throw new Error(result.error||'No se pudo completar la acción.');return result;
}
export default function AccountPage() {
 const [ready,setReady]=useState(false),[enabled,setEnabled]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
 const [account,setAccount]=useState<Account|null>(null),[email,setEmail]=useState(''),[code,setCode]=useState(''),[challenge,setChallenge]=useState(''),[name,setName]=useState(''),[phone,setPhone]=useState(''),[cooldown,setCooldown]=useState(0);
 useEffect(()=>{let alive=true;Promise.allSettled([request('config'),request('me')]).then(([config,me])=>{if(!alive)return;setEnabled(config.status==='fulfilled'&&config.value.emailEnabled===true);if(me.status==='fulfilled'){setAccount(me.value.account);setName(me.value.account.name);setPhone(me.value.account.phone);}setReady(true);});return()=>{alive=false;};},[]);
 useEffect(()=>{if(cooldown<=0)return;const timer=setTimeout(()=>setCooldown(v=>v-1),1000);return()=>clearTimeout(timer);},[cooldown]);
 async function run(work:()=>Promise<void>){if(busy)return;setBusy(true);setError('');setMessage('');try{await work();}catch(e){setError(e instanceof Error?e.message:'Intentá nuevamente.');}finally{setBusy(false);}}
 const send=()=>run(async()=>{const r=await request('challenge','POST',{email});setChallenge(r.challengeId);setCode('');setCooldown(60);setMessage('Te enviamos un código. Vence en 10 minutos.');});
 async function verify(e:FormEvent){e.preventDefault();await run(async()=>{const r=await request('verify','POST',{challengeId:challenge,code});setAccount(r.account);setName(r.account.name);setPhone(r.account.phone);setMessage('Ingresaste correctamente.');});}
 async function profile(e:FormEvent){e.preventDefault();await run(async()=>{const r=await request('profile','PUT',{name,phone});setAccount(r.account);setMessage('Tus datos quedaron guardados.');});}
 return <main className="account-page"><a href="/">← Volver a Natalia Sánchez Estética</a><section className="account-card"><p className="eyebrow">TU ESPACIO</p><h1>{account?'Mi cuenta':'Ingresar con mi email'}</h1>
 {!ready?<p>Cargando…</p>:account?<><p>{account.email}</p><form onSubmit={profile}><label>Nombre<input className="booking-input" value={name} onChange={e=>setName(e.target.value)} required minLength={2} maxLength={100} autoComplete="name"/></label><label>Teléfono con código de área<input className="booking-input" value={phone} onChange={e=>setPhone(e.target.value)} required type="tel" autoComplete="tel" placeholder="+54 362 1234567"/></label><button className="button-primary" disabled={busy}>Guardar mis datos</button></form><button className="text-link" disabled={busy} onClick={()=>run(async()=>{await request('logout','POST',{});setAccount(null);setChallenge('');setCode('');})}>Cerrar sesión</button></>:!enabled?<p>Estamos preparando el acceso por email. Mientras tanto, podés solicitar tu turno desde la web.</p>:challenge?<form onSubmit={verify}><p>Ingresá el código que enviamos a <strong>{email}</strong>.</p><label>Código de 6 dígitos<input className="booking-input" value={code} onChange={e=>setCode(e.target.value.replace(/\D/g,'').slice(0,6))} inputMode="numeric" autoComplete="one-time-code" pattern="[0-9]{6}" required maxLength={6}/></label><button className="button-primary" disabled={busy||code.length!==6}>Verificar e ingresar</button><button type="button" className="text-link" disabled={busy||cooldown>0} onClick={send}>{cooldown>0?'Reenviar en '+cooldown+' s':'Reenviar código'}</button><button type="button" className="text-link" disabled={busy} onClick={()=>{setChallenge('');setCode('');setError('');setMessage('');}}>Cambiar email</button></form>:<form onSubmit={e=>{e.preventDefault();void send();}}><p>Recibí un código en tu correo. Si es tu primera visita, crearemos tu cuenta al verificarlo.</p><label>Tu email<input className="booking-input" type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} required maxLength={254}/></label><button className="button-primary" disabled={busy||cooldown>0}>{busy?'Enviando…':cooldown>0?'Esperá '+cooldown+' s':'Recibir código'}</button></form>}
 {error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<p><a className="text-link" href="/#reservas">Solicitar turno →</a></p></section></main>;
}

